<template>
    <div class="page-container">
        <div class="default-box">
            <h1>Security</h1>
            <div class="action-card">
                <h2>Two-Factor Authentication</h2>
                <div v-if="!twoFactorEnabled">
                    <p>
                        Add an extra layer of security to your account by enabling two-factor authentication (2FA).
                    </p>
                    <div class="center-content"><button class="button-large" @click="enableTwoFactor">Enable Two-Factor
                            Authentication</button>
                    </div>
                    <div v-if="qrCodeUrl">
                        <p>Scan this QR code with your authenticator app:</p>
                        <img :src="qrCodeUrl" alt="QR Code for 2FA" />

                        <!-- OTP Verification Step -->
                        <div>
                            <p>Enter the code generated by your authenticator app:</p>
                            <input v-model="otp" type="text" placeholder="Enter OTP" />
                            <button class="button-large" @click="verifyTwoFactor">Verify</button>
                        </div>
                    </div>
                </div>
                <p v-if="twoFactorEnabled" class="success-message">
                    Two-Factor is enabled. You rock!
                </p>
            </div>
        </div>

        <div class="default-box-danger">
            <h2>Danger Zone</h2>
        </div>
        <div v-if="twoFactorEnabled" class="default-box-danger">
            <div class="delete-account-section">
                <button @click="disableTwoFactor" class="button-large-imp">
                    Disable Two-Factor Authentication
                </button>
            </div>
        </div>

        <div class="default-box-danger">
            <div class="delete-account-section">
                <h3>Deactivate Your Account</h3>
                <p class="delete-warning">
                    Deactivating your account will mark all associated data as inactive. In compliance with GDPR and AML
                    regulations, your data will be securely retained for a period of 90 days. During this time, your
                    account can be
                    reactivated if you choose to return. If no reactivation occurs within this period, all data will be
                    permanently
                    deleted. This action is final and cannot be undone after 90 days.
                </p><br>

                <!-- Initial Delete Button -->
                <button class="button-large-imp" v-if="!showFirstConfirmation && !showFinalConfirmation"
                    @click="showFirstConfirmation = true">
                    Deactivate My Account
                </button>

                <!-- First Confirmation -->
                <div v-if="showFirstConfirmation && !showFinalConfirmation">
                    <p class="confirmation-warning">
                        <br>Are you sure you want to deactivate your account?
                    </p>
                    <button class="confirm-button-acc" @click="showFinalConfirmation = true">
                        Yes, Proceed
                    </button>
                    <button @click="cancelDeletion">Cancel</button>
                </div>

                <!-- Final Confirmation -->
                <div v-if="showFinalConfirmation">
                    <p class="final-warning">
                        This is your final confirmation. Do you really want to deactivate your account?
                    </p>
                    <button class="confirm-button-acc"
                        @click="() => { console.log('Button Clicked'); finalizeDelete(); }">
                        Yes!
                    </button>
                    <button class="cancel-button-acc" @click="cancelDeletion">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import api from "@/api";
import QRCode from "qrcode";

export default {
    data() {
        return {
            twoFactorEnabled: false,
            qrCodeUrl: null,
            showSecondDeleteModal: false,
            showFirstConfirmation: false,
            showFinalConfirmation: false,
        };
    },
    created() {
        this.checkTwoFactorStatus();
    },
    methods: {
        // two-factor authentication check
        async checkTwoFactorStatus() {
            try {
                const response = await api.get("/user/security/2fa-status");
                this.twoFactorEnabled = response.data.enabled;
            } catch (error) {
                console.error("Failed to fetch 2FA status:", error);
            }
        },

        // Enable 2FA and fetch the QR code
        async enableTwoFactor() {
            try {
                const response = await api.post("/user/security/enable-2fa");
                const otpauthUrl = response.data.otpauthUrl;

                // Generate QR code
                QRCode.toDataURL(otpauthUrl, (err, url) => {
                    if (err) {
                        console.error("Failed to generate QR code:", err);
                        return;
                    }
                    this.qrCodeUrl = url;
                });
            } catch (error) {
                console.error("Failed to enable 2FA:", error);
                alert("Failed to enable Two-Factor Authentication.");
            }
        },

        // Verify the OTP entered by the user
        async verifyTwoFactor() {
            try {
                const response = await api.post("/user/security/verify-2fa", { otp: this.otp });
                if (response.data.message === "2FA verification successful.") {
                    alert("Two-Factor Authentication enabled successfully!");
                    this.twoFactorEnabled = true; // Update state
                    this.qrCodeUrl = null; // Clear the QR code
                }
            } catch (error) {
                console.error("Failed to verify 2FA:", error);
                alert("Invalid OTP. Please try again.");
            }
        },

        // Disable 2FA
        async disableTwoFactor() {
            try {
                const response = await api.post("/user/security/disable-2fa");
                if (response.data.message === "Two-factor authentication has been disabled.") {
                    alert("Two-Factor Authentication has been disabled.");
                    this.twoFactorEnabled = false; // Update state
                    this.qrCodeUrl = null; // Clear any residual QR code
                }
            } catch (error) {
                console.error("Failed to disable 2FA:", error);
                alert("Failed to disable Two-Factor Authentication.");
            }
        },

        // delete accout
        cancelDeletion() {
            this.showFirstConfirmation = false;
            this.showFinalConfirmation = false;
        },
        async finalizeDelete() {
            try {
                const response = await api.delete("/user/profile/delete");
                if (response.status === 200) {
                    alert("Account deleted successfully. You will be logged out.");
                    localStorage.removeItem("token");
                    this.$router.push("/login");
                } else {
                    throw new Error("Failed to delete account. Please try again.");
                }
            } catch (error) {
                console.error("Error deleting account:", error.message);
                alert("An error occurred while deleting your account. Please try again.");
            }
        },
    },
};
</script>
